-- use this file to map the AP item ids to your items
-- first value is the code of the target item and the second is the item type override (feel free to expand the table with any other values you might need (i.e. special initial values, increments, etc.)!)
-- here are the SM items as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/item_mapping.lua
BASE_ITEM_ID = 9999000000
local ITEM_LIST = {
	{ { "guardian_seal" } },
	{ { "guardian_seal" } },
	{ { "guardian_seal" } },
	{ { "guardian_seal" } },

	{ { "berries" } },
	{ { "eggs" } },
	{ { "insects" } },
	{ { "meat" } },
	{ { "mushrooms" } },
	{ { "roots" } },
	{ { "vegetables" } },
	{ { "fish" } },
	{ { "biscuits" } },
	{ { "jerky" } },
	{ { "pickled_goods" } },
	{ { "pie" } },
	{ { "porridge" } },
	{ { "skewers" } },
	{ { "paste" } },
	{ { "coats" } },
	{ { "boots" } },
	{ { "bricks" } },
	{ { "fabric" } },
	{ { "planks" } },
	{ { "pipes" } },
	{ { "parts" } },
	{ { "wildfire" } },
	{ { "ale" } },
	{ { "incense" } },
	{ { "scrolls" } },
	{ { "tea" } },
	{ { "training_gear" } },
	{ { "wine" } },
	{ { "clay" } },
	{ { "copper_ore" } },
	{ { "scales" } },
	{ { "crystalized_dew" } },
	{ { "grain" } },
	{ { "herbs" } },
	{ { "leather" } },
	{ { "plant_fiber" } },
	{ { "algae" } },
	{ { "reeds" } },
	{ { "resin" } },
	{ { "stone" } },
	{ { "salt" } },
	{ { "barrels" } },
	{ { "copper_bar" } },
	{ { "flour" } },
	{ { "dye" } },
	{ { "pottery" } },
	{ { "waterskins" } },
	{ { "amber" } },
	{ { "building_materials" } },
	{ { "crops" } },
	{ { "luxury" } },
	{ { "provisions" } },
	{ { "trade_goods" } },
	{ { "ancient_tablet" } },
	{ { "coal" } },
	{ { "oil" } },
	{ { "purging_fire" } },
	{ { "sea_marrow" } },
	{ { "tools" } },


	{ { "2 Starting Villagers" } },
    { { "15 Starting Crystallized Dew" } },
    { { "20 Starting Amber" } },
    { { "6 Starting Parts" } },
    { { "3 Starting Wildfire Essence" } },
    { { "20 Starting Pipes" } },
    { { "30 Starting Sea Marrow" } },
    { { "30 Starting Oil" } },
    { { "30 Starting Grain" } },
    { { "15 Starting Pack of Provisions" } },
    { { "25 Starting Mushrooms" } },
    { { "40 Starting Insects" } },
    { { "20 Starting Vegetables" } },
    { { "20 Starting Stone" } },
    { { "10 Starting Planks" } },
    { { "10 Starting Tools" } },
    { { "Survivor Bonding" } },

	--Blueprints
	{ { "foragers_camp" } },
	{ { "herbalists_camp" } },
	{ { "trappers_camp" } },
	{ { "fishing_hut" } },
	{ { "clay_pit" } },
	{ { "foresters_hut" } },
	{ { "greenhouse" } },
	{ { "herb_garden" } },
	--brineworks
	false,
	{ { "plantation" } },
	{ { "small_farm" } },
	{ { "advanced_rain_catcher" } },
	{ { "bakery" } },
	{ { "beanery" } },
	{ { "brick_oven" } },
	{ { "butcher" } },
	{ { "cellar" } },
	{ { "cookhouse" } },
	{ { "granary" } },
	{ { "grill" } },
	{ { "ranch" } },
	{ { "smokehouse" } },
	{ { "alchemist_hut" } },
	{ { "apothecary" } },
	{ { "artisan" } },
	{ { "brewery" } },
	{ { "brickyard" } },
	{ { "carpenter" } },
	{ { "clothier" } },
	{ { "cooperage" } },
	{ { "distillery" } },
	{ { "druid" } },
	{ { "furnace" } },
	{ { "kiln" } },
	{ { "leatherworks" } },
	{ { "lumber_mill" } },
	{ { "manufactory" } },
	{ { "press" } },
	{ { "provisioner" } },
	{ { "rain_mill" } },
	{ { "scribe" } },
	{ { "smelter" } },
	{ { "smithy" } },
	{ { "stamping_mill" } },
	{ { "supplier" } },
	{ { "tea_house" } },
	{ { "tinctury" } },
	{ { "tinkerer" } },
	{ { "toolshop" } },
	{ { "weaver" } },
	{ { "workshop" } },
	{ { "cobbler" } },


	{ { "pantry" } },
	{ { "cannery" } },


	{ { "bath_house" } },
	{ { "clan_hall" } },
	{ { "academy" } },
	{ { "guild_house" } },
	{ { "market" } },
	{ { "monastery" } },
	{ { "tavern" } },
	{ { "tea_doctor" } },
	{ { "temple" } },


	{ { "forum" } }
}

ITEM_MAPPING = {}

for index, mapping in ipairs(ITEM_LIST) do
    if mapping then
        ITEM_MAPPING[BASE_ITEM_ID + index - 1] = mapping
    end
end